/*
 * TicTacToe
 * Version 1.0
 * Copyright (C) GiusNiyyel, Inc - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Daniel Campos <giusniyyel@gmail.com>, August 2019
 */
package com.giusniyyel.tictactoe;

import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {
    
    public void transparency(){
        btnInfo.setOpaque(false);
        btnInfo.setContentAreaFilled(false);
        btnInfo.setBorderPainted(false);
        btnRules.setOpaque(false);
        btnRules.setContentAreaFilled(false);
        btnRules.setBorderPainted(false);
    }

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
        transparency();
        /* NOMBRE QUE MUESTRA */
        setTitle("Tic Tac Toe - El Juego del Gato");
        /* ICONO DEL SOFTWARE */
        setIconImage(new ImageIcon(getClass().getResource("/com/giusniyyel/tictactoe/src/icon.png")).getImage());
        /* REGLAS OTORGADAS AL JFRAME */
        setResizable(false);
        /* Fondo */
        this.setSize(1024,600);
        /*Null*/
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRules = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        lblmessage1 = new javax.swing.JLabel();
        lblmessage2 = new javax.swing.JLabel();
        vsPC = new javax.swing.JButton();
        vsPlayer = new javax.swing.JButton();
        lblmessage = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 235, 235));
        jLabel1.setText("¿No sabes jugar?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 340, 104, 50);

        btnRules.setBackground(new java.awt.Color(102, 102, 102));
        btnRules.setForeground(new java.awt.Color(51, 51, 51));
        btnRules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/tictactoe/src/question.png"))); // NOI18N
        btnRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRulesActionPerformed(evt);
            }
        });
        getContentPane().add(btnRules);
        btnRules.setBounds(490, 290, 40, 40);

        btnInfo.setBackground(new java.awt.Color(102, 102, 102));
        btnInfo.setForeground(new java.awt.Color(51, 51, 51));
        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/tictactoe/src/info.png"))); // NOI18N
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo);
        btnInfo.setBounds(980, 530, 35, 35);

        lblmessage1.setFont(new java.awt.Font("TeXGyreAdventor", 1, 24)); // NOI18N
        lblmessage1.setForeground(new java.awt.Color(235, 235, 235));
        lblmessage1.setText("PC INTELIGENTE");
        getContentPane().add(lblmessage1);
        lblmessage1.setBounds(650, 500, 180, 50);

        lblmessage2.setFont(new java.awt.Font("TeXGyreAdventor", 1, 24)); // NOI18N
        lblmessage2.setForeground(new java.awt.Color(235, 235, 235));
        lblmessage2.setText("MULTIJUGADOR");
        getContentPane().add(lblmessage2);
        lblmessage2.setBounds(200, 500, 180, 50);

        vsPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/tictactoe/src/playerpcclic.png"))); // NOI18N
        vsPC.setToolTipText("");
        vsPC.setPreferredSize(new java.awt.Dimension(300, 300));
        vsPC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/tictactoe/src/playerpcclic.png"))); // NOI18N
        vsPC.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/tictactoe/src/playerpc.png"))); // NOI18N
        vsPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsPCActionPerformed(evt);
            }
        });
        getContentPane().add(vsPC);
        vsPC.setBounds(590, 200, 300, 300);

        vsPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/tictactoe/src/playerclic.png"))); // NOI18N
        vsPlayer.setToolTipText("");
        vsPlayer.setPreferredSize(new java.awt.Dimension(300, 300));
        vsPlayer.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/tictactoe/src/playerclic.png"))); // NOI18N
        vsPlayer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/tictactoe/src/player.png"))); // NOI18N
        vsPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsPlayerActionPerformed(evt);
            }
        });
        getContentPane().add(vsPlayer);
        vsPlayer.setBounds(140, 200, 300, 300);

        lblmessage.setFont(new java.awt.Font("TeXGyreAdventor", 1, 24)); // NOI18N
        lblmessage.setForeground(new java.awt.Color(235, 235, 235));
        lblmessage.setText("¿QUÉ MODO DESEAS JUGAR?");
        getContentPane().add(lblmessage);
        lblmessage.setBounds(340, 150, 340, 50);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/tictactoe/src/BG.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 1024, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vsPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsPlayerActionPerformed
        dispose();
        Game game = new Game();
        game.setVisible(true);
    }//GEN-LAST:event_vsPlayerActionPerformed

    private void vsPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsPCActionPerformed
        dispose();
        GamePc game = new GamePc();
        game.setVisible(true);
    }//GEN-LAST:event_vsPCActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        dispose();
        About game = new About();
        game.setVisible(true);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRulesActionPerformed
        dispose();
        Rules game = new Rules();
        game.setVisible(true);
    }//GEN-LAST:event_btnRulesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnRules;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblmessage;
    private javax.swing.JLabel lblmessage1;
    private javax.swing.JLabel lblmessage2;
    private javax.swing.JButton vsPC;
    private javax.swing.JButton vsPlayer;
    // End of variables declaration//GEN-END:variables
}
